name: Tests

# This action should run on every commit
on: [push, pull_request]
env:
  # override poetry virtual env location
  # required for actions/setup-python@v3 can cache poetry correctly
  POETRY_VIRTUALENVS_IN_PROJECT: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
        env:
          # skip the check that throws on `main` branch
          SKIP: no-commit-to-branch
  test:
    name: Test Python scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: d3-scripts
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest # tests whether our Python code works