name: Tests

# This action should run on every commit
on: [push, pull_request]
env:
  # override poetry virtual env location
  # required for actions/setup-python@v3 can cache poetry correctly
  POETRY_VIRTUALENVS_IN_PROJECT: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
        env:
          # skip the check that throws on `main` branch
          SKIP: no-commit-to-branch
  test:
    name: Test Python scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: d3-cli
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - run: poetry run pytest # tests whether our Python code works
  publish:
    name: Publish pypi package
    permissions:
      # required to bump version
      contents: write
    runs-on: ubuntu-latest
    # d3build is slow, so only run if lint passes
    needs: [pre-commit, test]
    defaults:
        run:
          working-directory: d3-cli
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip uninstall -y keyring
          poetry --version
      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          POETRY_HTTP_BASIC_PYPI_USERNAME: NquiringMinds
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry version patch
          poetry build
          poetry publish
